
#define MODEM_UART_TX_PIN 17
#define MODEM_UART_RX_PIN 16
#define MODEM_UART_RTS_PIN 25
#define MODEM_UART_CTS_PIN 26
#define MODEM_UART_RX_BUFFER_SIZE 16384
#define MODEM_UART_TX_BUFFER_SIZE 1024
#define MODEM_UART_PATTERN_QUEUE_SIZE 20
#define MODEM_UART_EVENT_QUEUE_SIZE 30
#define MODEM_UART_EVENT_TASK_STACK_SIZE 2048
#define MODEM_UART_EVENT_TASK_PRIORITY 5
#define MODEM_PPP_AUTH_USERNAME "adslppp@telefonicanetpa"
#define MODEM_PPP_AUTH_PASSWORD "adslppp"